add device-list and device-details components
ThingooKNI/frontend pull request #37
Opened 2021-03-07 18:40 UTC by Arcywojak

2021-03-07 23:12 UTC, TheWildTree requested changes
good work. just a quick pass, will review more thoroughly later.

one rather important thing: when writing CSS, please add a space between the selector and the opening bracket (`.class{` -> `.class {`) for readibility - our linter will start enforcing this in the upcoming days.

in addition to that, please take a look at the issues reported by the linter during CI.

2021-03-07 23:12 UTC, thewildtree commented on src/app/pages/device-details/device-details.component.html
> +        <div class="device-bacis-info">
class name typo

2021-03-07 23:12 UTC, thewildtree commented on src/app/pages/device-list/device-card/device-card.component.scss
> +.device-card{
device cards should react to hovering and clicking them (material ripple should be used for the latter)

2021-03-07 23:12 UTC, thewildtree commented on src/app/pages/device-list/device-card/device-card.component.scss
> +    border: 1px solid lightgray;
no borders needed here (might want to add a less intrusive one on hover though)

2021-03-07 23:12 UTC, thewildtree commented on src/app/pages/device-list/device-list.component.ts
> +    console.log(this.authService);
looks like a leftover?

2021-03-07 23:12 UTC, thewildtree commented on src/app/pages/device-list/device-list.component.ts
> +  public fakeData: any = [
nit: let's avoid naming variables like this - even though it's a mock-up, this should be named along the likes of `devicesList` to avoid unnecessary work when implementing actual API data fetching later on.

same applies to `device-details`.

2021-03-19 15:15 UTC, BartlomiejRasztabiga commented
@Arcywojak Are you still working on this?

2021-03-28 14:33 UTC, TheWildTree requested changes
good work, a few more touches needed 👍 

about tests failures: I have to figure out how to solve the dependency issue we're seeing, it's fine to remove tests for the components you've added for now - they don't have any complex logic in them anyway.

2021-03-28 14:33 UTC, thewildtree commented on src/app/pages/device-list/device-card/device-card.component.scss
> +  border-radius: 6px;
should be moved inside `.device-card` (`&-wrapper`)

2021-03-28 14:33 UTC, thewildtree commented on src/app/pages/device-details/device-details.component.ts
> +      console.log(params?.id);
I think we can remove this? (along with the constructor DI)

2021-03-28 14:33 UTC, thewildtree commented on src/app/pages/device-list/device-list.component.ts
> +    './device-card/device-card.component.scss',
pretty sure adding this isn't needed

2021-03-28 14:33 UTC, TheWildTree commented on src/app/pages/device-list/device-list.component.scss
> +.device-list-page-wrapper {
same thing as with the `device-card` - you can move this inside the `.device-list` ruleset, so it reads along the lines of:
```css
.device-list {
  &-page-wrapper {}
}
```
also, just `-wrapper` would be fine I think 👍

2021-03-28 14:33 UTC, TheWildTree commented on src/app/pages/device-list/device-card/device-card.component.scss
> +  border-radius: 6px;
I think we can remove this one - `mat-card` has a default `border-radius` of 4px which is fine and easier to keep consistent. don't forget to change the one in the `-wrapper`, though 😄

2021-03-28 14:33 UTC, TheWildTree commented on src/app/pages/device-details/device-details.component.scss
> +.entity-item {
the thing with these is that they're `mat-card`s on top of another `mat-card`. I see you've tried to change the background colour to make it look better (a bit of a dimmer one and we'd be done) but there's a bit of a better way to do that.

Material has something called 'elevation', which is what we'll wanna use in cases like this one. About elevation on dark themes: [might be helpful to read that](https://material.io/design/color/dark-theme.html#properties). Basically it adds a more 'distanced' shadow to indicate that this element is, indeed, on top of another one + adds a slight white overlay which blends with the background, creating the effect we're looking for. 

Angular Material provides a `mat-elevation-zN` class out of the box - we probably want to use `z2` here - but that only adds the shadow. If you want, you can manually change the background colour to what the Material one linked above specifies for a 2dp elevation (7% white overlay) or find a way to do it automatically - I know [Material's official elevation package](https://www.npmjs.com/package/@material/elevation) provides something like this, but I haven't tested it yet. Up to you 👍

2021-04-02 17:12 UTC, TheWildTree approved these changes

2021-04-02 17:12 UTC, merged